M48
; DRILL file {KiCad (6.0.5)} date Sun Jun 19 19:15:52 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-19T19:15:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X3.7402Y-2.3811
X3.7429Y-2.3386
X3.8795Y-2.3358
X3.8807Y-2.3807
T2
X3.6134Y-2.3846
T0
M30
